# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 4.0
  DisplayCopNames: true
  Exclude:
    - 'bin/rails'
    - 'db/*'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'notes/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  NewCops: enable
FactoryBot/AssociationStyle:
  EnforcedStyle: explicit
Layout/LineLength:
  Max: 120
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/ExtraSpacing:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
Layout/TrailingWhitespace:
  Enabled: true
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/EmptyBlock:
  Exclude:
    - 'spec/factories/*'
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - 'app/api/v1/*.rb'
    - 'app/api/v1/**/*.rb'
    - 'config/**/*'
    - 'spec/**/*'
Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*'
RSpec/ExampleLength:
  Max: 10
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/mailers/**/*'
RSpec/MultipleMemoizedHelpers:
  Max: 15
RSpec/NestedGroups:
  Max: 5
RSpec/SpecFilePathFormat:
  Exclude:
    - 'spec/api/v1/auth_api/*_spec.rb'
    - 'spec/api/v1/diaries_api/*_spec.rb'
    - 'spec/api/v1/foods_api/*_spec.rb'
Style/AccessorGrouping:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/ExponentialNotation:
  Enabled: true
Style/FormatStringToken:
  Enabled: false
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
